Change/Change/Models/Photo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Photo
    {
        public int PhotoId { get; set; }
        [Display(Name = "商品")]
        public Nullable<int> ProductId { get; set; }
        [Display(Name = "图片地址")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string PhotoUrl { get; set; }

        public virtual Product Product { get; set; }
    }
}

Change/Change/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Change.Models;

namespace Change.Controllers
{
    [AdminAuthentication]
    public class PhotosController : Controller
    {
        private ChangeDBEntities db = new ChangeDBEntities();

        // GET: Photos
        public ActionResult Index()
        {
            var photo = db.Photo.Include(p => p.Product);
            return View(photo.ToList());
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create 为某商品添加图片信息
        public ActionResult Create(int id)
        {
            //获取商品ID
            ViewBag.ProductId = id;
            ViewBag.Product = db.Product.Include("Photo").First(p => p.ProductId == id);
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PhotoId,ProductId,PhotoUrl")] Photo photo, HttpPostedFileBase PhotoUrl)
        {
            if (ModelState.IsValid)
            {
                //上传图片
                if (PhotoUrl != null)
                {
                    photo.PhotoUrl = "/images/Goods/" + PhotoUrl.FileName;
                    PhotoUrl.SaveAs(Server.MapPath(photo.PhotoUrl));
                }
                db.Photo.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Create", new { id = photo.ProductId });//返回图片管理页面
            }

            ViewBag.ProductId = photo.ProductId;
            ViewBag.Product = db.Product.First(p => p.ProductId == photo.ProductId);
            return View(photo);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = new SelectList(db.Product, "ProductId", "Title", photo.ProductId);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhotoId,ProductId,PhotoUrl")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = new SelectList(db.Product, "ProductId", "Title", photo.ProductId);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photo.Find(id);
            db.Photo.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Create", new { id = photo.ProductId });//返回图片管理页面
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Change/Change/Views/Photos/Create.cshtml
@model Change.Models.Photo

@{
    ViewBag.Title = "添加图片";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    Product p = (Product)ViewBag.Product;
}

<h2>添加图片</h2>
@using (Html.BeginForm("Create", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <fieldset class="form-horizontal">
        <legend>图片信息</legend>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId, new { @Value = p.ProductId })

        <div class="form-group">
            <label class="control-label col-md-2" for="PhotoUrl">所属商品:</label>
            <div class="col-md-10">
                <a href="/Products/Details?id=@p.ProductId">@(p.Title)</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="PhotoUrl" id="PhotoUrl" />
                @Html.ValidationMessageFor(model => model.PhotoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=" 保存 " class="btn btn-default" />
            </div>
        </div>
    </fieldset>
}
<!--展示所有该商品图片-->
    <div  id="photos">
        @foreach (var item in p.Photo)
        {
            <dl>
                <dt><img src="@item.PhotoUrl" /></dt>
                <dd>@Html.ActionLink("删除", "Delete", new { id = item.PhotoId })</dd>
            </dl>
        }
        <div class="clear"></div>
    </div>
    <div>
        @Html.ActionLink("返回商品列表", "Index","Products")
    </div>

Change/Change/Views/Photos/Delete.cshtml
@model Change.Models.Photo

@{
    ViewBag.Title = "删除图片";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>删除图片</h2>

<h3>是否确认删除?</h3>
<div>
    <h4>图片信息</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            所属商品：
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Title)
        </dd>

        <dt>
            图片：
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.PhotoUrl)" />
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=" 确认删除 " class="btn btn-default" /> |
            @Html.ActionLink("返回图片列表", "Create",new { id=Model.ProductId})
        </div>
    }
</div>

Change/Change/Views/Photos/Details.cshtml
@model Change.Models.Photo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PhotoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Change/Change/Views/Photos/Edit.cshtml
@model Change.Models.Photo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PhotoId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhotoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhotoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Change/Change/Views/Photos/Index.cshtml
@model IEnumerable<Change.Models.Photo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PhotoUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PhotoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PhotoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PhotoId })
        </td>
    </tr>
}

</table>